### ISSUE TITLE
Renew on name with "expired" status fails

### ISSUE THREAD

**Issue by unsystemizer** [phelix/nameGUI#3]
![image](https://cloud.githubusercontent.com/assets/13134193/9629668/f82f588c-51a6-11e5-8f77-86bffbfd7363.png)

Both my NameCoin Core and NameGUI are installed on E:.
Don't know why c:\ appears in the screenshot.

Probably Renew operation on Expired name shouldn't be allowed by the GUI?

**Comment by phelixbtc** [comment]
Yes, there are a couple of cases with ugly error messages like this. The c: drive seems to come from my build. It might take some time until this gets fixed.

**Comment by unsystemizer** [comment]
Another related behavior is that on expired items I get this error, but when I enter the same thing in "New name" and hit Register, I get a notification of "Pending transaction" - does that mean that the expired item isn't registered, or is that just a best effort type of try? 
I remember before if you wanted to register a taken name using the old Namecoin-Qt GUI it wouldn't work. But on the other hand in NameGUI I don't see this name that was accepted ("Pending transaction") by NameGUI appear in NameGUI later, so I'm not sure how that part works compared to Namecoin-Qt before.

Alarmingly, for this "Pending Transaction" above I just checked Namecoin Core GUI (Namecoin Core version v0.11.99.0-unk (32-bit)) and filtered all transaction for "This week" and I don't see any transactions. I am concerned that some may be silently failing.

**Comment by phelixbtc** [comment]
I call this fixed for now as of https://github.com/phelix/nameGUI/commit/4aadcb4297b497c6c7dcead1d5fbecad1e8df1ce
