### ISSUE TITLE
[Enh]: Keyboard shortcuts

### ISSUE THREAD

**Issue by unsystemizer** [phelix/nameGUI#4]
It'd be nice to be able to operate the GUI by using keyboard shortcuts.

**Comment by phelixbtc** [comment]
You mean shortcuts to renew, configure, etc? Yes, that would be nice.

**Comment by unsystemizer** [comment]
Yes. 
Because clicking on names can be tiresome, but of course most people don't have many names, so for the majority of users it won't be that necessary.

**Comment by phelixbtc** [comment]
I also have in mind selecting multiple names and then renewing / updating? / transfering? all at once.

**Comment by phelixbtc** [comment]
Shortcuts for renew and configure per https://github.com/phelix/nameGUI/commit/d77e14c6f9be0aaa0d5c5f290a271e714aba3883

These should be the most important for now... closing.
