### ISSUE TITLE
Informational messages could be logged to the GUI

### ISSUE THREAD

**Issue by unsystemizer** [phelix/nameGUI#5]
Maybe info messages from namecoind could be logged to the GUI (or ignored?)
This is when namecoind is catching up with the blockchain. I did not try to do anything that requires an up to date blockchain, so "Blockhain up to date: no" is enough (unless I try something that requires it to be up to date).

![image](https://cloud.githubusercontent.com/assets/13134193/9703287/4dc3901c-54b1-11e5-92ac-5fd0e846b647.png)

**Comment by phelixbtc** [comment]
This looks like it happened because a lookup of a name via the register entry field failed. Yeah, it should express it failed some more comfortable way.

**Comment by phelix** [comment]
Fixed per https://github.com/phelix/nameGUI/pull/8
